import type { ToolManifest, ToolVerdict } from "./types";

/**
 * Emits the file a developer drops into their own app.
 *
 * Only tools that survived the scan are registered. Blocked ones are still
 * written out, commented, with the finding attached, so the developer sees
 * what was withheld and why rather than silently receiving a shorter list.
 */
export function generateIntegration(
  manifest: ToolManifest,
  verdicts: ToolVerdict[],
): string {
  const blockedNames = new Set(
    verdicts.filter((v) => v.verdict === "blocked").map((v) => v.tool),
  );

  const header = `/**
 * WebMCP tools generated by WebMCP Forge from ${manifest.repoLabel}
 * Generated ${manifest.generatedAt}
 *
 * ${manifest.tools.length} tool(s) discovered, ${manifest.tools.length - blockedNames.size} registered,
 * ${blockedNames.size} withheld by the security scan.
 *
 * Import this once from a client component. The API is SecureContext-only,
 * so it needs https or localhost.
 */

const modelContext =
  (typeof document !== "undefined" && document.modelContext) ||
  (typeof navigator !== "undefined" && navigator.modelContext) ||
  null;

/** Generated tools reach the network through here so egress stays observable. */
async function gatedFetch(method, url, body) {
  const target = new URL(url, window.location.origin);
  if (target.origin !== window.location.origin) {
    throw new Error("WebMCP Forge policy: " + target.origin + " is not this origin.");
  }
  const response = await fetch(target, {
    method,
    headers: body ? { "content-type": "application/json" } : undefined,
    body: body ? JSON.stringify(body) : undefined,
  });
  return response.json();
}

export function registerGeneratedTools() {
  if (!modelContext) return () => {};
`;

  const blocks = manifest.tools.map((tool) => {
    const verdict = verdicts.find((v) => v.tool === tool.name);
    const blocked = blockedNames.has(tool.name);
    const reasons = (verdict?.findings ?? [])
      .map((finding) => `   *   [${finding.severity.toUpperCase()}] ${finding.title} — ${finding.evidence}`)
      .join("\n");

    const query = Object.entries(tool.paramLocations)
      .filter(([, location]) => location === "query")
      .map(([name]) => name);
    const bodyParams = Object.entries(tool.paramLocations)
      .filter(([, location]) => location === "body")
      .map(([name]) => name);
    const pathParams = Object.entries(tool.paramLocations)
      .filter(([, location]) => location === "path")
      .map(([name]) => name);

    const lines: string[] = [];
    lines.push(`    let path = ${JSON.stringify(tool.endpoint.path)};`);
    for (const name of pathParams) {
      lines.push(
        `    path = path.replace("{${name}}", encodeURIComponent(String(input[${JSON.stringify(name)}])));`,
      );
    }
    if (query.length > 0) {
      lines.push(`    const query = new URLSearchParams();`);
      for (const name of query) {
        lines.push(
          `    if (input[${JSON.stringify(name)}] != null) query.set(${JSON.stringify(name)}, String(input[${JSON.stringify(name)}]));`,
        );
      }
      lines.push(`    if (query.toString()) path += "?" + query.toString();`);
    }
    const bodyExpr =
      bodyParams.length > 0
        ? `{ ${bodyParams.map((name) => `${name}: input[${JSON.stringify(name)}]`).join(", ")} }`
        : "undefined";
    lines.push(
      `    return gatedFetch(${JSON.stringify(tool.endpoint.method)}, path, ${bodyExpr});`,
    );

    const body = `  modelContext.registerTool({
    name: ${JSON.stringify(tool.name)},
    description: ${JSON.stringify(tool.description)},
    inputSchema: ${JSON.stringify(tool.inputSchema, null, 2).split("\n").join("\n    ")},
    annotations: { readOnlyHint: ${tool.annotations.readOnlyHint} },
    execute: async (input) => {
${lines.join("\n")}
    },
  });`;

    if (!blocked) {
      return `  // from ${tool.origin.source} (${tool.origin.capabilityId})\n${body}\n`;
    }

    return `  /* WITHHELD by the security scan:
${reasons}
   *
${body
  .split("\n")
  .map((line) => `   * ${line}`)
  .join("\n")}
   */\n`;
  });

  const names = manifest.tools
    .filter((tool) => !blockedNames.has(tool.name))
    .map((tool) => JSON.stringify(tool.name));

  const footer = `
  return () => {
    for (const name of [${names.join(", ")}]) {
      try { modelContext.unregisterTool(name); } catch {}
    }
  };
}
`;

  return `${header}\n${blocks.join("\n")}${footer}`;
}
